# site name
site_name: 暮色蒼然
short_name: Ursule

# Master info. It won't work if the one from (author|authorLink|avatar|authorDesc) be written in post.md
webmaster:
  name: Ursule
  avatar: /images/favicon.png
  home: https://ursulefj.github.io
  desc:

# CSP Mode, true means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
csp_enable: true

# Read Mode. day or night
read_mode: day

# favicon
favicon: /images/favicon.png
# unique avatar
avatar_show: false
avatar_image: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
home_page_sort: -1
# Home page article shown number
home_article_shown: 10

# your site build time or domain buy time
site_building_time: 01/23/2020

# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
  前端: frontend
  后端: backend

# Customize left navigation menus. faName is FontAwesome style name
# left_nav_menus:
#   - uri: help
#     title: 帮助
#     faName: fa-question-circle

# cover info config
cover_title: Ursule blog
cover_description: '人生就像一场旅行，不在乎目的地，在乎的只是沿途的风景，以及看风景的心情'

# cover sns info
sns:
  twitter: https://twitter.com/ursule_pp
  github: https://github.com/ursulefj
  weixin: wxid_emrvf7znlx4n22

# page pop qrcode
donateImg:
snsQRCode:

# article declare. default content in languages
post_declare: true

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## Analytics setting. Google default
analytics:
  enable: false
  google_analytics_id:

## Google AdSense.
adsense:
  auto: true
  client_id:
  page_tb_id:
  archive_id:
  tags_id:
  post_inner_id:
  post_left_id:
  post_right_id:

## Comments settings. Disqus
##                  | Gitment（Introduction: https://imsun.net/posts/gitment-introduction/）
##                  | gitalk  (Official website: https://gitalk.github.io/)
comments:
  enable: false
  disqus_shortname:
  gitalk:
    on: true
    clientID:
    clientSecret:
    owner:
    repo:
    admin: ['your name']
    perPage: 6
    pagerDirection: 'last'
  gitment:
    repo:
    githubID:
    ClientID:
    ClientSecret:
    lazy: true

# Git-pages server info (Coding Pages|Github Pages)
server_name:
server_url:

mathjax:
  enable: false

## Baidu ziyuan auto-commit. see https://ziyuan.baidu.com/
baidu_auto_push: false

## MIIT Info. see https://beian.miit.gov.cn/#/Integrated/index
miit_license: ## 例：京ICP备xxxxx号
